### ISSUE TITLE
learning models from the hiragana.txt

### ISSUE THREAD

**Issue by vfxbro** [thomasoca/hiragana-recognizer-cnn#1]
Will I be able to create learning models from the hiragana.txt file?

only for example in Chinese or Mongolian?

**Comment by thomasoca** [comment]
No you can't. Actually I only use hiragana.txt file as a reference when exploring the data, maybe I will delete the file to minimize confusion. If you want to create new learning models, you need to provide the training data and update the [hiragana_cnn.py](https://github.com/thomasoca/hiragana-recognizer-cnn/blob/master/hiragana_cnn.py) on this part:
```
hiragana = np.load("hiragana.npz")['arr_0'].reshape([-1, 127, 128]).astype(np.float32)
hiragana = hiragana / np.max(hiragana)
X_df = np.zeros([n_char * 160, img_rows, img_cols], dtype=np.float32)
y_df = np.repeat(np.arange(n_char), 160)
```
I store the training data as a .npz file, then load it to the model as an array. I don't know what the type of the data that you will use, but in principle, you can load the training data as array-like type data to run the Tensorflow model.

**Comment by vfxbro** [comment]
Thank you very much!

I am new to this business and could you help me create such a file for the old Mongolian writing?

by itself not free!

**Comment by vfxbro** [comment]
<img width="1758" alt="Снимок экрана 2021-01-17 в 23 08 32" src="https://user-images.githubusercontent.com/4408699/104854641-f20da600-5918-11eb-8b3c-c4beadffabe4.png">

**Comment by thomasoca** [comment]
unfortunately, I neither have any experiences nor knowledge about providing such file (digitized handwriting) as I used a public database for this project. Usually you can found such database on academic journals etc. as they tend to have a more dedicated research in this area.
